### ISSUE TITLE
双时间控件上，默认没有填写选中的时间

### ISSUE THREAD

**Issue by coolguy001tv** [cd-fe/react-component#27]
双时间控件上，下方选择框中明明已经选中了2个时间，但是上面的输入框却没有填写，容易引起误导。建议填入选中的时间。

**Comment by darkty2009** [comment]
因为提供了确定按钮，所以，只有点击确定按钮的时候，才会在上方的输入框中生效

**Comment by coolguy001tv** [comment]
太不人性化了，那就不应该默认选中。既然默认选中了，就应该填写进去哇
