### ISSUE TITLE
按照example.jsx 中的方法按需加载依赖报错！

### ISSUE THREAD

**Issue by pangbi** [cd-fe/react-component#29]
按照例子中的example.jsx 中提供的方法按需加载依赖，能够正常分成chunk，但是运行的时候报出如下错误
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

**Comment by darkty2009** [comment]
页面切换，并且示例功能是否正常？
