### ISSUE TITLE
webpack配置错误，package.json依赖不完整

### ISSUE THREAD

**Issue by coolguy001tv** [cd-fe/react-component#30]
1. 项目依赖了node-sass，但是package.json没有包含，导致执行npm run lib报错
2. npm run example时报NODE_ENV错误

**Comment by darkty2009** [comment]
1. sass-loader 依赖了 node-sass 模块，如果发现没有，可能是npm安装过程中被墙了
2. mac和windows上关于NODE_ENV的设置方式不一致，可查看 package.json 里
   mac上使用  NODE_ENV=development [commands]
   windows上使用 set NODE_ENV=development&[command]

发现这种错误的时候，可自行修改一下 package.json 或者等我有时间换成另外一种运行方式来判断开发和线上
